services:
  app-proof:
    image: node:20.5-alpine3.17@sha256:c8ae1785da54b802347d06e826d5ae127fc7851114803ee4098f782d46ba40a9
    working_dir: /app
    volumes:
      - ${HOME}/.npm:/home/node/.npm ## pass through npm folder from host for caching
      - ./:/app
    ports:
      - 3000:3000
    command: ["node_modules/.bin/next", "dev"]